version: "3"

services:
  reverseproxy:
    image: iiotsuite/nginx
    build: ./nginx
    restart: unless-stopped
    ports:
      - "${PROXY_PORT}:80"
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload --with-stream; done & nginx -g "daemon off;"'''

  telegraf:
    image: telegraf:1.25.0
    environment:
      - INFLUX_TOKEN=${INFLUX_CONFIG_TOKEN}
    restart: always
    command:
      - telegraf
      - --config
      - http://influx:8086/api/v2/telegrafs/${INFLUX_CONFIG_ID}
      - --watch-config
      - poll
    depends_on:
      - influx

  kapacitor:
    image: kapacitor
    environment:
      KAPACITOR_HOSTNAME: kapacitor
      KAPACITOR_INFLUXDB_0_URLS_0: http://influx:8086
    volumes:
      - ./data/kapacitor:/var/lib/kapacitor
    ports:
      - "9092:9092"

  chronograf:
    image: chronograf
    volumes:
      - ./data/chronograf:/var/lib/chronograf
    ports:
      - "8888:8888"

  nodered:
    image: iiotsuite/nodered
    build: ./nodered
    user: root
    restart: unless-stopped
    environment:
      - TZ=Europe/Madrid
      - NODE_RED_ENABLE_PROJECTS=true
    volumes:
      - ./data/nodered:/data
    extra_hosts:
      - "host.docker.internal:host-gateway"

  influx:
    image: iiotsuite/influx
    build: ./influx
    user: root
    #restart: unless-stopped
    environment:
      - TZ=Europe/Madrid
      - DOCKER_INFLUXDB_INIT_MODE=${DOCKER_INFLUXDB_INIT_MODE}
      - DOCKER_INFLUXDB_INIT_USERNAME=${DOCKER_INFLUXDB_INIT_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${DOCKER_INFLUXDB_INIT_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${DOCKER_INFLUXDB_INIT_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${DOCKER_INFLUXDB_INIT_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}

    ports:
      - "${INFLUX_PORT}:8086"
    volumes:
      - ./data/influx:/var/lib/influxdb
      - ./data/influx2:/var/lib/influxdb2
      - ./data/influx2config:/etc/influxdb2

  grafana:
    image: iiotsuite/grafana
    build: ./grafana
    user: root
    environment:
      - GF_SERVER_DOMAIN=${DOMAIN}
      - GF_SERVER_ROOT_URL=${GRAFANA_ROOT}
      - GF_SERVER_SERVE_FROM_SUB_PATH=${GRAFANA_SUBPATH}
    restart: unless-stopped
    volumes:
      - ./data/grafana/lib:/var/lib/grafana
